### ISSUE TITLE
Documentation of Preferences implies support for iOS only

### ISSUE THREAD

**Issue by matthewpavkov** [apache/cordova-plugin-statusbar#113]
The documentation of the *Preferences* implies that only iOS is supported.

Specifically, for the *Preferences* `StatusBarOverlaysWebView`, `StatusBarBackgroundColor`, `StatusBarStyle`, and `StatusBarDefaultScrollToTop`, each paragraph begins with the language "On iOS", which implies it may only be supported on iOS. Since this is not the case, I recommend the documentation be updated for clarity.

**Comment by janpio** [comment]
So those 4 preferences also work on Android equal to how they work on iOS?

**Comment by matthewpavkov** [comment]
Here is what I'm seeing in Android 8.1 (emulator), Cordova 8.1.2, Cordova Plugin Statusbar 2.4.2:

- `StatusBarOverlaysWebView` seems to have no effect
- `StatusBarBackgroundColor` changes the background color of the status bar per the value you pass in (ex. #555555)
- `StatusBarStyle` with value `default` has the area for the status bar completely black (black background with black text/icons)
  - Using the value `default` results in black text/icons
  - Using the value `lightcontent` results in white text/icons
  - Using the value `blacktranslucent` results in white text/icons
  - Using the value `blackopaque` results in white text/icons
  - Using an empty value results in white text/icons
- `StatusBarDefaultScrollToTop` seems to have no effect

**Comment by jcesarmobile** [comment]
They used to be iOS only, when the methods and preferences were supported in other platforms the "On iOS" was not removed, but should be.

**Comment by breautek** [comment]
I don't use all the StatusBar properties, but in my apps I do use `StatusBarOverlaysWebview` and I support android versions from 4.1 to latest.

I have several different physical devices to test with:
- CAT B15 Phone (Android 4.1) - Overlay has no effect
- Samsung Galaxy s4 (Android 4.4) - Overlay has no effect
- Samsung Galaxy s5 (Android 6.0) - Overlay works
- Samsung Galaxy S5 Neo (Android 7) - Overlay works
- Samsung Galaxy Note 9 (Android 8.1) - Overlay works
- Google Pixel (Android 9) - Overlay works

All of my apps are built with cordova cli 8.1.2, cordova-android 7, and statusbar 2.4.2.

I believe overlay webview works on Android 5.0 and later because translucent status bars is possible as of Android 5.0 and greater.

> * `StatusBarOverlaysWebView` seems to have no effect

I also would like to point out that there is a bug that was previously reported at #122 where the plugin doesn't respect the config.xml preference and instead just defaults to overlay true. The ticket reported it for iOS but it appears to happen on Android as well. Using the javascript API `StatusBar.overlaysWebView(true);` definitely does work on the android devices I listed.

The documentation, at least for the overlay preference I think is definitely misleading.

**Comment by janpio** [comment]
Thanks for that investigation @breautek. Are you up to submitting a PR that updates the documentation? That would be awesome.

(Also mention that it also affects Android in #122 please - when someone finds the time to investigate this will be important to know.)

**Comment by breautek** [comment]
> Thanks for that investigation @breautek. Are you up to submitting a PR that updates the documentation? That would be awesome.
> 
> (Also mention that it also affects Android in #122 please - when someone finds the time to investigate this will be important to know.)

Yah I could make a PR to update the documentation.  

#122 is related in the sense that the native code doesn't appear to do what the documentation claims, I haven't tested it on android but I looked through the source and didn't see any point where it reads the preferences and sets the overlay value appropriately, but I could be simply looking in the wrong place. I can make an actual test and investigate further just to confirm. Unfortunately the original reporter closed the ticket.

**Comment by janpio** [comment]
> Unfortunately the original reporter closed the ticket.
Fixed that.
