### ISSUE TITLE
Font color on android

### ISSUE THREAD

**Issue by EnzoDLP** [apache/cordova-plugin-statusbar#131]
We can't use black font on a statusbar in white

**Comment by breautek** [comment]
Please include the following information:
- config.xml statusbar preferences
- Your android platform version (can be found by running `cordova platform list`)
- The plugin version (can be found by running `cordova plugin list`)
- And your device & android version that you're running.
- Anything else you think is relevant (e.g. it only happens if you call certain APIs)

It may also be helpful if you can provide a test git repository that includes the bare minimum to reproduce your issue. It can also serve is a testing ground for a fix.

**Comment by EnzoDLP** [comment]
- Config XML preferences :      
`<preference name="StatusBarBackgroundColor" value="#FFFFFF" />`
I use in app.component with ionic 
`this.statusBar.backgroundColorByHexString('#fff') (import { StatusBar } from '@ionic-native/status-bar';)

- Android version : android 7.1.4

- Plugin version : cordova-plugin-statusbar 2.4.2 "StatusBar"

- Cordova version : 8.1.2 (cordova-lib@8.1.1)

- My device : Huawei P Smart Android 8.0

I tried several think with the plugin but no one give me black font on the statusbar. I got a white status bar with a white text (ANDROID)

**Comment by breautek** [comment]
Ok, so if I understand correctly you're trying to get a white status bar, with black font.

There are two different properties:
- `StatusBarStyle` - Which handles the font style. 
- `StatusBarBackgroundColor` - Which handles the background color.

So you're already using `StatusBarBackgroundColor` but you're missing `StatusBarStyle`.

> StatusBarStyle (status bar style, defaults to lightcontent). Set the status bar style. Available options default, lightcontent, blacktranslucent, blackopaque.

The following line in your config.xml should give you a black/dark font 
`<preference name="StatusBarStyle" value="default" />`

**Comment by EnzoDLP** [comment]
It's working !! Thanks man ahah ! I was so stupid using the ionic plugin instead of the preference default...

**Comment by breautek** [comment]
No problem, glad it resolved your issue. "lightcontent" is the cordova default value, which is for a dark background. So I don't think it's necessary ionic ;)

If you feel like the plugin should be modified at all (including documentation), then you can leave the ticket open and document what you think should be changed. Otherwise please close the ticket.

Cheers!
