### ISSUE TITLE
2.4.3 BROKEN - Replacement Release Desperately Needed

### ISSUE THREAD

**Issue by codeconsole** [apache/cordova-plugin-statusbar#216]
The latest version released has been broken since Jun 19, 2019 and the code was fixed sometime in 2020.

Can you please release from the fixed master branch so that users will not have to use the github version?

Once you do a release, you can finally close this Issue:

https://github.com/apache/cordova-plugin-camera/issues/566

Thanks!

**Comment by curtgrimes** [comment]
@erisu @mosabab are there plans to publish a new version to npm?

**Comment by PabbleDabble** [comment]
Heya, just wanted to chime in, apologies if this is already known by everyone, but you can use npm to install from a specific hash directly until the npm registry is updated with new version.

```
$ cordova plugin add https://github.com/apache/cordova-plugin-statusbar#3ebae213dfd9798dc1c674fbbeb4d0ad49947c1d
```
Alternatively, you can also fork the plugin to your local repo and install from a local directory.

You can look at the repo network here to pick the hash you want - https://github.com/apache/cordova-plugin-statusbar/network

Again, I know these are just alternatives, just a suggestion in case you desperately needed a section of code and don't like installing via repo (we do not do this because we like our versions to be locked so no changes can be implemented without us specifically knowing)

**Comment by erisu** [comment]
[v3.0.0](https://www.npmjs.com/package/cordova-plugin-statusbar/v/3.0.0) has been released.
